
site_name: '.conf26 OBS1217 - Break Down Silos: Achieve Unified Observability with ThousandEyes and Splunk'
site_description: Interactive Workshop instructions for .conf26 OBS1217 - Break Down Silos: Achieve Unified Observability with ThousandEyes and Splunk
site_author: Antonio Jimenez
site_url: https://ajimenez1503.github.io/splunk.conf-2026-OBS1217/
repo_url: https://github.com/ajimenez1503/splunk.conf-2026-OBS1217

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: README.md
  - Getting Started:
    - ThousandEyes: getting_started/thousandeyes.md
    - Log In to Splunk Observability Cloud: getting_started/login_splunk_observability.md
    - Log In to Splunk Show: getting_started/login_splunk_show.md
  - Service Map:
    - Create the Splunk APM Integration: service_map/basic/create_splunk_apm_integration.md
    - Create ThousandEyes HTTP Test: service_map/basic/create_thousandeyes_http_test.md
    - View the Service Map: service_map/basic/view_service_map.md
  - Splunk Observability Cloud:
    - Create a Metric Stream to Splunk Observability Cloud: splunk_observability/create_metric_stream_to_splunk_observability.md
    - Create a Trace Stream to Splunk Observability Cloud: splunk_observability/create_trace_stream_to_splunk_observability.md
    - Visualize ThousandEyes Metrics in Splunk Observability Cloud: splunk_observability/visualize_metrics_in_splunk_observability.md
    - Visualize ThousandEyes Traces in Splunk Observability Cloud: splunk_observability/visualize_traces_in_splunk_observability.md
  - Splunk Core:
    - Create a Metrics Stream to Splunk Core: splunk_core/create_metrics_stream_to_splunk_cloud_enterprise.md
    - Create a Logs Stream to Splunk Core: splunk_core/create_logs_stream_to_splunk_cloud_enterprise.md
    - Visualize ThousandEyes Metrics in Splunk Core: splunk_core/visualize_metrics_in_splunk_cloud_enterprise.md
    - Visualize ThousandEyes Logs in Splunk Core: splunk_core/visualize_logs_in_splunk_cloud_enterprise.md
  - Cisco ThousandEyes App for Splunk:
    - Authenticate the ThousandEyes User: thousandeyes_splunk_app/authenticate_thousandeyes_user.md
    - Create a Test Stream - Metrics Input: thousandeyes_splunk_app/test_metrics_stream_input.md
    - Create an Activity Log Input: thousandeyes_splunk_app/activity_logs_input.md
    - Create a Test Stream - Traces Input: thousandeyes_splunk_app/test_traces_stream_input.md
  - Splunk IT Service Intelligence:
    - [Draft] Ingest ThousandEyes Alerts: 
    - [Draft] Configure Content Pack:
theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime


markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true

plugins: 
  - search
  - open-in-new-tab

copyright: |
  &copy; 2026 <a href="https://cisco.com"  target="_blank" rel="noopener">Cisco Systems, Inc.</a>
